name: Main/Single entrypoint pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  prepare_env:
    name: Set up variables and stuff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
# --------
    
  trigger_build_flow:
    runs-on: ubuntu-latest
    # outputs:
      # output1: ${{ some_variable }}
    steps:
      - name: Call Build pipeline
        uses: ./.github/workflows/build-pipeline@main
# --------

  trigger_email_flow:
    runs-on: windows-latest
    needs: trigger_build_flow
    # if:  ${{ some_variable }} == 'true'
    steps:
      - name: Call Email pipeline
        uses: ./.github/workflows/email-pipeline@main
