name: Main/Single entrypoint pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  prepare_env:
    name: Set up variables and stuff
    runs-on: ubuntu-latest
    # outputs:
      # output1: ${{ some_variable }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
# --------
    
  trigger_build_flow:
    needs: prepare_env
    uses: ./.github/workflows/build-pipeline.yml
# --------

  trigger_email_flow:
    needs: [prepare_env, trigger_build_flow]
    uses: ./.github/workflows/email-pipeline.yml
    # if:  ${{ some_variable }} == 'true'
